using System;
Console.WriteLine("========================================");
Console.WriteLine("Работу выполнили: Чичикин и Мартемьянов");
Console.WriteLine("Группа: 3831");
Console.WriteLine("========================================\n");
Console.Write("Введите имя: ");
string firstName = Console.ReadLine();
Console.Write("Введите фамилию: ");
string lastName = Console.ReadLine();
Console.Write("Введите год рождения: ");
string yearInput = Console.ReadLine();
int birthYear = Convert.ToInt32(yearInput);
int currentYear = DateTime.Now.Year;
int age = currentYear - birthYear;
Console.WriteLine($"\nДобавлен пользователь {firstName} {lastName}, возраст - {age}");
